version: "3"

services:
  db:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-store:/var/lib/postgres/data
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: dev
volumes:
  postgres-store:
