name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test-user
          POSTGRES_PASSWORD: test-password
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: yarn install, build, and test
        run: |
          yarn install --immutable --immutable-cache --check-cache
          yarn migrate:test
          yarn test
        env:
          DATABASE_URL: postgresql://test-user:test-password@localhost:5432/test
          CI: true
